name             'shinken'
maintainer       'EverTrue, Inc.'
maintainer_email 'eric.herot@evertrue.com'
license          'Apache 2.0'
description      'Installs/Configures shinken'
long_description 'Installs/Configures shinken'
version          '1.1.0'

depends 'ark'
depends 'apt'
depends 'python'
